services:
  - type: web
    name: neuraforge-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main_prod.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: OXXO_CLIENT_ID
        sync: false
      - key: OXXO_SECRET_KEY
        sync: false
      - key: WEB_APP_URL
        fromService:
          type: web

  - type: worker
    name: neuraforge-monetizador
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_publica/monetizador.py
    autoDeploy: true
    envVars:
      - key: WEB_APP_URL
        fromService:
          type: web